### ISSUE TITLE
wiki contribution link does not work

### ISSUE THREAD

**Issue by stahl-riesa** [qooxdoo/qooxdoo#9169]
here in the wiki in the contribution section where is a link to http://qooxdoo.org/community/contribution which isnt working.

**Comment by level420** [comment]
I think this is fixed in master.
@stahl-riesa could you please verify this by e.g. visiting http://www.qooxdoo.org/devel/toc.html ?
Thank you!

**Comment by stahl-riesa** [comment]
Still broken.

open: https://github.com/qooxdoo/qooxdoo
scroll down to: Contributing
last sentence:
"For more information see http://qooxdoo.org/community/contribution." This Links is broken!

**Comment by cboulanger** [comment]
Closing - old website will be retired soon.
