### ISSUE TITLE
'click' event not being fired for menu button in Firefox 66

### ISSUE THREAD

**Issue by milandamen** [qooxdoo/qooxdoo#9645]
**Description**
Since Firefox 66, the 'click' event is no longer being fired for qx.ui.menu.Button widgets. It still works in older versions of Firefox and newest Chrome.

**Reproduction**

    var menuBar = new qx.ui.menubar.MenuBar();
    
    var menuItem = new qx.ui.menubar.Button('Menu item');
    var submenu = new qx.ui.menu.Menu();
    var submenuItem = new qx.ui.menu.Button('Submenu item 1');
    
    submenu.add(submenuItem);
    menuItem.setMenu(submenu);
    menuBar.add(menuItem);
    
    this.getRoot().add(menuBar);
    
    submenuItem.addListener('click', function (event) {
      alert('submenu item 1 clicked');
    });
    
    
    
    
    var label = new qx.ui.basic.Label('Some label');
    this.getRoot().add(label, {top: 100});
    
    var menu2 = new qx.ui.menu.Menu();
    var item2 = new qx.ui.menu.Button('Submenu item 2');
    
    menu2.add(item2);
    label.setContextMenu(menu2);
    
    item2.addListener('click', function (event) {
      alert('submenu item 2 clicked');
    });

1. Open a menu. It does not matter if the menu was opened using a widget contextmenu (rightclick) or using a MenuBar Button.
2. Click on a menu item in the menu.

**Actual result**
No 'click' event gets fired by the browser, so Qooxdoo does not dispatch it to the rest of the application.

**Expected result**
The 'click' event gets fired by the browser and Qooxdoo will dispatch it.

**Possible cause**
This is speculation, but I think Qooxdoo might be stopping the browser from firing the 'click' event, because the browser fires 'pointerdown' and 'pointerup' correctly.
I have tried reproducing this with pure HTML without Qooxdoo and it fired the 'click' event correctly.

**Workaround**
Listen to 'execute' or 'tap' instead of 'click' on the menu button.

**Comment by cboulanger** [comment]
Which version of qooxdoo are you using? We are just in the process of backporting fixes from v6 to v5 and this might already be fixed in version 6. @level420, can you comment?

**Comment by milandamen** [comment]
I am using the tip of master at the moment (7ce1e45ba062a04871032847b6a3727a6c24fe2a). It's still broken on Firefox 66.0.1.

**Comment by oetiker** [comment]
this is still present in that latest firefox and latest playground

<http://www.qooxdoo.org/qxl.playground/#%7B%22code%22%3A%22%252F%252F%2520Create%2520the%2520menu%250Avar%2520menu%2520%253D%2520new%2520qx.ui.menu.Menu()%253B%250A%250Avar%2520closeButton%2520%253D%2520new%2520qx.ui.menu.Button(%2522Close%2522)%253B%250A%250Amenu.add(closeButton)%253B%250A%250Avar%2520button%2520%253D%2520new%2520qx.ui.form.MenuButton(%2522Menu%2522%252C%2520null%252C%2520menu)%253B%250A%250A%252F%252F%2520Document%2520is%2520the%2520application%2520root%250Avar%2520doc%2520%253D%2520this.getRoot()%253B%250A%250A%252F%252F%2520Add%2520button%2520to%2520document%2520at%2520fixed%2520coordinates%250Adoc.add(button%252C%250A%257B%250A%2520%2520left%2520%253A%2520100%252C%250A%2520%2520top%2520%2520%253A%252050%250A%257D)%253B%250A%250A%252F%252F%2520Add%2520an%2520event%2520listener%250AcloseButton.addListener(%2522click%2522%252C%2520function(e)%2520%257B%250A%2520%2520alert(%2522Hello%2520World!%2522)%253B%250A%257D)%253B%22%2C%20%22mode%22%3A%22ria%22%7D>

**Comment by hkollmann** [comment]
Done with https://github.com/qooxdoo/qooxdoo/pull/9889
